// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: prism.proto

package prismpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Prism_EncodeRequest_FullMethodName   = "/prism.transport.v1.Prism/EncodeRequest"
	Prism_DecodeResponse_FullMethodName  = "/prism.transport.v1.Prism/DecodeResponse"
	Prism_DecodeSSE_FullMethodName       = "/prism.transport.v1.Prism/DecodeSSE"
	Prism_DecodeSSEStream_FullMethodName = "/prism.transport.v1.Prism/DecodeSSEStream"
	Prism_EncodeStream_FullMethodName    = "/prism.transport.v1.Prism/EncodeStream"
	Prism_Convert_FullMethodName         = "/prism.transport.v1.Prism/Convert"
	Prism_ConvertStream_FullMethodName   = "/prism.transport.v1.Prism/ConvertStream"
	Prism_ListProviders_FullMethodName   = "/prism.transport.v1.Prism/ListProviders"
	Prism_Capability_FullMethodName      = "/prism.transport.v1.Prism/Capability"
	Prism_Ping_FullMethodName            = "/prism.transport.v1.Prism/Ping"
)

// PrismClient is the client API for Prism service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Prism is the gRPC binding of the protocol-conversion gateway daemon
// (transport/ARCHITECTURE.md §5.4). Every RPC maps 1:1 to the daemon
// method set and returns the D5 envelope {value, diagnostics}; streaming
// RPCs (EncodeStream / ConvertStream) send one envelope per event.
type PrismClient interface {
	// EncodeRequest converts text to a provider JSON request body.
	EncodeRequest(ctx context.Context, in *EncodeRequestReq, opts ...grpc.CallOption) (*Envelope, error)
	// DecodeResponse extracts plain text from a provider JSON response.
	DecodeResponse(ctx context.Context, in *DecodeResponseReq, opts ...grpc.CallOption) (*Envelope, error)
	// DecodeSSE decodes provider SSE text into a JSON array of events (sync).
	DecodeSSE(ctx context.Context, in *DecodeSSEReq, opts ...grpc.CallOption) (*Envelope, error)
	// DecodeSSEStream decodes provider SSE text and streams one envelope per
	// event (server-streaming; mirrors the HTTP SSE / UDS / WS streaming path).
	DecodeSSEStream(ctx context.Context, in *DecodeSSEReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Envelope], error)
	// EncodeStream converts text to a streaming (stream:true) provider request
	// (sync: returns the request JSON, not an event stream).
	EncodeStream(ctx context.Context, in *EncodeStreamReq, opts ...grpc.CallOption) (*Envelope, error)
	// Convert translates a provider payload to another provider via Lucent IR.
	Convert(ctx context.Context, in *ConvertReq, opts ...grpc.CallOption) (*Envelope, error)
	// ConvertStream translates streamed SSE text between providers (sync:
	// returns the target SSE text).
	ConvertStream(ctx context.Context, in *ConvertStreamReq, opts ...grpc.CallOption) (*Envelope, error)
	// ListProviders returns registered provider names.
	ListProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error)
	// Capability returns the capability declaration for a provider.
	Capability(ctx context.Context, in *CapabilityReq, opts ...grpc.CallOption) (*Envelope, error)
	// Ping is a health probe.
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
}

type prismClient struct {
	cc grpc.ClientConnInterface
}

func NewPrismClient(cc grpc.ClientConnInterface) PrismClient {
	return &prismClient{cc}
}

func (c *prismClient) EncodeRequest(ctx context.Context, in *EncodeRequestReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_EncodeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) DecodeResponse(ctx context.Context, in *DecodeResponseReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_DecodeResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) DecodeSSE(ctx context.Context, in *DecodeSSEReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_DecodeSSE_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) DecodeSSEStream(ctx context.Context, in *DecodeSSEReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Prism_ServiceDesc.Streams[0], Prism_DecodeSSEStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecodeSSEReq, Envelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Prism_DecodeSSEStreamClient = grpc.ServerStreamingClient[Envelope]

func (c *prismClient) EncodeStream(ctx context.Context, in *EncodeStreamReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_EncodeStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) Convert(ctx context.Context, in *ConvertReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) ConvertStream(ctx context.Context, in *ConvertStreamReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_ConvertStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) ListProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderList)
	err := c.cc.Invoke(ctx, Prism_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) Capability(ctx context.Context, in *CapabilityReq, opts ...grpc.CallOption) (*Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Envelope)
	err := c.cc.Invoke(ctx, Prism_Capability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, Prism_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrismServer is the server API for Prism service.
// All implementations must embed UnimplementedPrismServer
// for forward compatibility.
//
// Prism is the gRPC binding of the protocol-conversion gateway daemon
// (transport/ARCHITECTURE.md §5.4). Every RPC maps 1:1 to the daemon
// method set and returns the D5 envelope {value, diagnostics}; streaming
// RPCs (EncodeStream / ConvertStream) send one envelope per event.
type PrismServer interface {
	// EncodeRequest converts text to a provider JSON request body.
	EncodeRequest(context.Context, *EncodeRequestReq) (*Envelope, error)
	// DecodeResponse extracts plain text from a provider JSON response.
	DecodeResponse(context.Context, *DecodeResponseReq) (*Envelope, error)
	// DecodeSSE decodes provider SSE text into a JSON array of events (sync).
	DecodeSSE(context.Context, *DecodeSSEReq) (*Envelope, error)
	// DecodeSSEStream decodes provider SSE text and streams one envelope per
	// event (server-streaming; mirrors the HTTP SSE / UDS / WS streaming path).
	DecodeSSEStream(*DecodeSSEReq, grpc.ServerStreamingServer[Envelope]) error
	// EncodeStream converts text to a streaming (stream:true) provider request
	// (sync: returns the request JSON, not an event stream).
	EncodeStream(context.Context, *EncodeStreamReq) (*Envelope, error)
	// Convert translates a provider payload to another provider via Lucent IR.
	Convert(context.Context, *ConvertReq) (*Envelope, error)
	// ConvertStream translates streamed SSE text between providers (sync:
	// returns the target SSE text).
	ConvertStream(context.Context, *ConvertStreamReq) (*Envelope, error)
	// ListProviders returns registered provider names.
	ListProviders(context.Context, *Empty) (*ProviderList, error)
	// Capability returns the capability declaration for a provider.
	Capability(context.Context, *CapabilityReq) (*Envelope, error)
	// Ping is a health probe.
	Ping(context.Context, *Empty) (*Pong, error)
	mustEmbedUnimplementedPrismServer()
}

// UnimplementedPrismServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrismServer struct{}

func (UnimplementedPrismServer) EncodeRequest(context.Context, *EncodeRequestReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeRequest not implemented")
}
func (UnimplementedPrismServer) DecodeResponse(context.Context, *DecodeResponseReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeResponse not implemented")
}
func (UnimplementedPrismServer) DecodeSSE(context.Context, *DecodeSSEReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeSSE not implemented")
}
func (UnimplementedPrismServer) DecodeSSEStream(*DecodeSSEReq, grpc.ServerStreamingServer[Envelope]) error {
	return status.Error(codes.Unimplemented, "method DecodeSSEStream not implemented")
}
func (UnimplementedPrismServer) EncodeStream(context.Context, *EncodeStreamReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeStream not implemented")
}
func (UnimplementedPrismServer) Convert(context.Context, *ConvertReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedPrismServer) ConvertStream(context.Context, *ConvertStreamReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertStream not implemented")
}
func (UnimplementedPrismServer) ListProviders(context.Context, *Empty) (*ProviderList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedPrismServer) Capability(context.Context, *CapabilityReq) (*Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method Capability not implemented")
}
func (UnimplementedPrismServer) Ping(context.Context, *Empty) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPrismServer) mustEmbedUnimplementedPrismServer() {}
func (UnimplementedPrismServer) testEmbeddedByValue()               {}

// UnsafePrismServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrismServer will
// result in compilation errors.
type UnsafePrismServer interface {
	mustEmbedUnimplementedPrismServer()
}

func RegisterPrismServer(s grpc.ServiceRegistrar, srv PrismServer) {
	// If the following call panics, it indicates UnimplementedPrismServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Prism_ServiceDesc, srv)
}

func _Prism_EncodeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).EncodeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_EncodeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).EncodeRequest(ctx, req.(*EncodeRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_DecodeResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeResponseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).DecodeResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_DecodeResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).DecodeResponse(ctx, req.(*DecodeResponseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_DecodeSSE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeSSEReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).DecodeSSE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_DecodeSSE_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).DecodeSSE(ctx, req.(*DecodeSSEReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_DecodeSSEStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DecodeSSEReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrismServer).DecodeSSEStream(m, &grpc.GenericServerStream[DecodeSSEReq, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Prism_DecodeSSEStreamServer = grpc.ServerStreamingServer[Envelope]

func _Prism_EncodeStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).EncodeStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_EncodeStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).EncodeStream(ctx, req.(*EncodeStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).Convert(ctx, req.(*ConvertReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_ConvertStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).ConvertStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_ConvertStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).ConvertStream(ctx, req.(*ConvertStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).ListProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_Capability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).Capability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_Capability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).Capability(ctx, req.(*CapabilityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Prism_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prism_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Prism_ServiceDesc is the grpc.ServiceDesc for Prism service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prism_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prism.transport.v1.Prism",
	HandlerType: (*PrismServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncodeRequest",
			Handler:    _Prism_EncodeRequest_Handler,
		},
		{
			MethodName: "DecodeResponse",
			Handler:    _Prism_DecodeResponse_Handler,
		},
		{
			MethodName: "DecodeSSE",
			Handler:    _Prism_DecodeSSE_Handler,
		},
		{
			MethodName: "EncodeStream",
			Handler:    _Prism_EncodeStream_Handler,
		},
		{
			MethodName: "Convert",
			Handler:    _Prism_Convert_Handler,
		},
		{
			MethodName: "ConvertStream",
			Handler:    _Prism_ConvertStream_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _Prism_ListProviders_Handler,
		},
		{
			MethodName: "Capability",
			Handler:    _Prism_Capability_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Prism_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DecodeSSEStream",
			Handler:       _Prism_DecodeSSEStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prism.proto",
}
