// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: prism.proto

package prismpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the D5 result shape: {"value":…,"diagnostics":[…]}.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_prism_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Envelope) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// Diagnostic corresponds to lux.ConversionDiagnostic.
type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_prism_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{1}
}

func (x *Diagnostic) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Diagnostic) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Diagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type EncodeRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeRequestReq) Reset() {
	*x = EncodeRequestReq{}
	mi := &file_prism_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeRequestReq) ProtoMessage() {}

func (x *EncodeRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeRequestReq.ProtoReflect.Descriptor instead.
func (*EncodeRequestReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{2}
}

func (x *EncodeRequestReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EncodeRequestReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DecodeResponseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeResponseReq) Reset() {
	*x = DecodeResponseReq{}
	mi := &file_prism_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeResponseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponseReq) ProtoMessage() {}

func (x *DecodeResponseReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponseReq.ProtoReflect.Descriptor instead.
func (*DecodeResponseReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{3}
}

func (x *DecodeResponseReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DecodeResponseReq) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type DecodeSSEReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Sse           string                 `protobuf:"bytes,2,opt,name=sse,proto3" json:"sse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeSSEReq) Reset() {
	*x = DecodeSSEReq{}
	mi := &file_prism_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeSSEReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeSSEReq) ProtoMessage() {}

func (x *DecodeSSEReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeSSEReq.ProtoReflect.Descriptor instead.
func (*DecodeSSEReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{4}
}

func (x *DecodeSSEReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DecodeSSEReq) GetSse() string {
	if x != nil {
		return x.Sse
	}
	return ""
}

type EncodeStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeStreamReq) Reset() {
	*x = EncodeStreamReq{}
	mi := &file_prism_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeStreamReq) ProtoMessage() {}

func (x *EncodeStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeStreamReq.ProtoReflect.Descriptor instead.
func (*EncodeStreamReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{5}
}

func (x *EncodeStreamReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EncodeStreamReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ConvertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromProvider  string                 `protobuf:"bytes,1,opt,name=from_provider,json=fromProvider,proto3" json:"from_provider,omitempty"`
	ToProvider    string                 `protobuf:"bytes,2,opt,name=to_provider,json=toProvider,proto3" json:"to_provider,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertReq) Reset() {
	*x = ConvertReq{}
	mi := &file_prism_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertReq) ProtoMessage() {}

func (x *ConvertReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertReq.ProtoReflect.Descriptor instead.
func (*ConvertReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertReq) GetFromProvider() string {
	if x != nil {
		return x.FromProvider
	}
	return ""
}

func (x *ConvertReq) GetToProvider() string {
	if x != nil {
		return x.ToProvider
	}
	return ""
}

func (x *ConvertReq) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ConvertReq) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ConvertStreamReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromProvider  string                 `protobuf:"bytes,1,opt,name=from_provider,json=fromProvider,proto3" json:"from_provider,omitempty"`
	ToProvider    string                 `protobuf:"bytes,2,opt,name=to_provider,json=toProvider,proto3" json:"to_provider,omitempty"`
	Sse           string                 `protobuf:"bytes,3,opt,name=sse,proto3" json:"sse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertStreamReq) Reset() {
	*x = ConvertStreamReq{}
	mi := &file_prism_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertStreamReq) ProtoMessage() {}

func (x *ConvertStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertStreamReq.ProtoReflect.Descriptor instead.
func (*ConvertStreamReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertStreamReq) GetFromProvider() string {
	if x != nil {
		return x.FromProvider
	}
	return ""
}

func (x *ConvertStreamReq) GetToProvider() string {
	if x != nil {
		return x.ToProvider
	}
	return ""
}

func (x *ConvertStreamReq) GetSse() string {
	if x != nil {
		return x.Sse
	}
	return ""
}

type CapabilityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityReq) Reset() {
	*x = CapabilityReq{}
	mi := &file_prism_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityReq) ProtoMessage() {}

func (x *CapabilityReq) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityReq.ProtoReflect.Descriptor instead.
func (*CapabilityReq) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityReq) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_prism_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{9}
}

type ProviderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderList) Reset() {
	*x = ProviderList{}
	mi := &file_prism_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderList) ProtoMessage() {}

func (x *ProviderList) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderList.ProtoReflect.Descriptor instead.
func (*ProviderList) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderList) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_prism_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_prism_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_prism_proto_rawDescGZIP(), []int{11}
}

func (x *Pong) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_prism_proto protoreflect.FileDescriptor

const file_prism_proto_rawDesc = "" +
	"\n" +
	"\vprism.proto\x12\x12prism.transport.v1\"b\n" +
	"\bEnvelope\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12@\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x1e.prism.transport.v1.DiagnosticR\vdiagnostics\"R\n" +
	"\n" +
	"Diagnostic\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"B\n" +
	"\x10EncodeRequestReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"C\n" +
	"\x11DecodeResponseReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"<\n" +
	"\fDecodeSSEReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x10\n" +
	"\x03sse\x18\x02 \x01(\tR\x03sse\"A\n" +
	"\x0fEncodeStreamReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x8a\x01\n" +
	"\n" +
	"ConvertReq\x12#\n" +
	"\rfrom_provider\x18\x01 \x01(\tR\ffromProvider\x12\x1f\n" +
	"\vto_provider\x18\x02 \x01(\tR\n" +
	"toProvider\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\"j\n" +
	"\x10ConvertStreamReq\x12#\n" +
	"\rfrom_provider\x18\x01 \x01(\tR\ffromProvider\x12\x1f\n" +
	"\vto_provider\x18\x02 \x01(\tR\n" +
	"toProvider\x12\x10\n" +
	"\x03sse\x18\x03 \x01(\tR\x03sse\"+\n" +
	"\rCapabilityReq\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\a\n" +
	"\x05Empty\",\n" +
	"\fProviderList\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\" \n" +
	"\x04Pong\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa0\x06\n" +
	"\x05Prism\x12S\n" +
	"\rEncodeRequest\x12$.prism.transport.v1.EncodeRequestReq\x1a\x1c.prism.transport.v1.Envelope\x12U\n" +
	"\x0eDecodeResponse\x12%.prism.transport.v1.DecodeResponseReq\x1a\x1c.prism.transport.v1.Envelope\x12K\n" +
	"\tDecodeSSE\x12 .prism.transport.v1.DecodeSSEReq\x1a\x1c.prism.transport.v1.Envelope\x12S\n" +
	"\x0fDecodeSSEStream\x12 .prism.transport.v1.DecodeSSEReq\x1a\x1c.prism.transport.v1.Envelope0\x01\x12Q\n" +
	"\fEncodeStream\x12#.prism.transport.v1.EncodeStreamReq\x1a\x1c.prism.transport.v1.Envelope\x12G\n" +
	"\aConvert\x12\x1e.prism.transport.v1.ConvertReq\x1a\x1c.prism.transport.v1.Envelope\x12S\n" +
	"\rConvertStream\x12$.prism.transport.v1.ConvertStreamReq\x1a\x1c.prism.transport.v1.Envelope\x12L\n" +
	"\rListProviders\x12\x19.prism.transport.v1.Empty\x1a .prism.transport.v1.ProviderList\x12M\n" +
	"\n" +
	"Capability\x12!.prism.transport.v1.CapabilityReq\x1a\x1c.prism.transport.v1.Envelope\x12;\n" +
	"\x04Ping\x12\x19.prism.transport.v1.Empty\x1a\x18.prism.transport.v1.PongBAZ?github.com/morning-start/prism/transport/daemon/prismpb;prismpbb\x06proto3"

var (
	file_prism_proto_rawDescOnce sync.Once
	file_prism_proto_rawDescData []byte
)

func file_prism_proto_rawDescGZIP() []byte {
	file_prism_proto_rawDescOnce.Do(func() {
		file_prism_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prism_proto_rawDesc), len(file_prism_proto_rawDesc)))
	})
	return file_prism_proto_rawDescData
}

var file_prism_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_prism_proto_goTypes = []any{
	(*Envelope)(nil),          // 0: prism.transport.v1.Envelope
	(*Diagnostic)(nil),        // 1: prism.transport.v1.Diagnostic
	(*EncodeRequestReq)(nil),  // 2: prism.transport.v1.EncodeRequestReq
	(*DecodeResponseReq)(nil), // 3: prism.transport.v1.DecodeResponseReq
	(*DecodeSSEReq)(nil),      // 4: prism.transport.v1.DecodeSSEReq
	(*EncodeStreamReq)(nil),   // 5: prism.transport.v1.EncodeStreamReq
	(*ConvertReq)(nil),        // 6: prism.transport.v1.ConvertReq
	(*ConvertStreamReq)(nil),  // 7: prism.transport.v1.ConvertStreamReq
	(*CapabilityReq)(nil),     // 8: prism.transport.v1.CapabilityReq
	(*Empty)(nil),             // 9: prism.transport.v1.Empty
	(*ProviderList)(nil),      // 10: prism.transport.v1.ProviderList
	(*Pong)(nil),              // 11: prism.transport.v1.Pong
}
var file_prism_proto_depIdxs = []int32{
	1,  // 0: prism.transport.v1.Envelope.diagnostics:type_name -> prism.transport.v1.Diagnostic
	2,  // 1: prism.transport.v1.Prism.EncodeRequest:input_type -> prism.transport.v1.EncodeRequestReq
	3,  // 2: prism.transport.v1.Prism.DecodeResponse:input_type -> prism.transport.v1.DecodeResponseReq
	4,  // 3: prism.transport.v1.Prism.DecodeSSE:input_type -> prism.transport.v1.DecodeSSEReq
	4,  // 4: prism.transport.v1.Prism.DecodeSSEStream:input_type -> prism.transport.v1.DecodeSSEReq
	5,  // 5: prism.transport.v1.Prism.EncodeStream:input_type -> prism.transport.v1.EncodeStreamReq
	6,  // 6: prism.transport.v1.Prism.Convert:input_type -> prism.transport.v1.ConvertReq
	7,  // 7: prism.transport.v1.Prism.ConvertStream:input_type -> prism.transport.v1.ConvertStreamReq
	9,  // 8: prism.transport.v1.Prism.ListProviders:input_type -> prism.transport.v1.Empty
	8,  // 9: prism.transport.v1.Prism.Capability:input_type -> prism.transport.v1.CapabilityReq
	9,  // 10: prism.transport.v1.Prism.Ping:input_type -> prism.transport.v1.Empty
	0,  // 11: prism.transport.v1.Prism.EncodeRequest:output_type -> prism.transport.v1.Envelope
	0,  // 12: prism.transport.v1.Prism.DecodeResponse:output_type -> prism.transport.v1.Envelope
	0,  // 13: prism.transport.v1.Prism.DecodeSSE:output_type -> prism.transport.v1.Envelope
	0,  // 14: prism.transport.v1.Prism.DecodeSSEStream:output_type -> prism.transport.v1.Envelope
	0,  // 15: prism.transport.v1.Prism.EncodeStream:output_type -> prism.transport.v1.Envelope
	0,  // 16: prism.transport.v1.Prism.Convert:output_type -> prism.transport.v1.Envelope
	0,  // 17: prism.transport.v1.Prism.ConvertStream:output_type -> prism.transport.v1.Envelope
	10, // 18: prism.transport.v1.Prism.ListProviders:output_type -> prism.transport.v1.ProviderList
	0,  // 19: prism.transport.v1.Prism.Capability:output_type -> prism.transport.v1.Envelope
	11, // 20: prism.transport.v1.Prism.Ping:output_type -> prism.transport.v1.Pong
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_prism_proto_init() }
func file_prism_proto_init() {
	if File_prism_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prism_proto_rawDesc), len(file_prism_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prism_proto_goTypes,
		DependencyIndexes: file_prism_proto_depIdxs,
		MessageInfos:      file_prism_proto_msgTypes,
	}.Build()
	File_prism_proto = out.File
	file_prism_proto_goTypes = nil
	file_prism_proto_depIdxs = nil
}
